export const SEARCH_ARTIST_START = 'SEARCH_ARTIST_START';
export const SEARCH_ARTIST_FAILURE = 'SEARCH_ARTIST_FAILURE';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_END = 'SEARCH_ARTIST_END';